# Project Identification
sonar.projectKey=ConnectWe_Application
sonar.projectName=ConnectWe_Application
sonar.projectVersion=1.0

# Source Code Locations
sonar.sources=Client/connect-gather,Server

# Exclusions (VERY IMPORTANT)
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,\
**/terraform/**,**/ansible/**,**/Jenkins/**,**/docker/**,**/*.tf,**/*.yml,**/*.yaml,**/app.js,**/server.js

# Language Settings
sonar.language=js

# Encoding
sonar.sourceEncoding=UTF-8
